# Generated by Django 3.2.1 on 2021-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210508_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Запись на собитие', 'verbose_name_plural': 'Записи на собития'},
        ),
        migrations.AddField(
            model_name='event',
            name='features',
            field=models.ManyToManyField(related_name='свойства', to='events.Feature'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category'),
        ),
    ]
