# Generated by Django 3.2.1 on 2021-05-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210508_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Свойство события', 'verbose_name_plural': 'Свойства события'},
        ),
    ]
