# Generated by Django 3.2.1 on 2021-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_feature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Запись на событие', 'verbose_name_plural': 'Записи на события'},
        ),
        migrations.AddField(
            model_name='event',
            name='idn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Оценка пользователя'),
        ),
    ]
