# Generated by Django 3.2.1 on 2021-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210514_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='idn',
        ),
    ]
