# Generated by Django 3.2.5 on 2021-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='features',
            field=models.ManyToManyField(related_name='features', to='events.Feature', verbose_name='Особенности'),
        ),
    ]
