# Generated by Django 3.2.5 on 2021-07-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='is_send',
            new_name='is_sent',
        ),
    ]
